services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  terraxcel-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: terraxcel-server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      OUTPUT_DIR: /output
    volumes:
      - ./output:/output
    depends_on:
      - db